# Generated by Django 5.2.4 on 2025-07-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_cliente_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$LK8dIq9dP5YnWuMuNL0NDd$wrhm1CTDAWAv1ey0DhjbuuBy8nC2ml8U2Q6cFz+PUDg=', max_length=128),
        ),
    ]
