# Generated by Django 5.2.4 on 2025-07-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$foiyf6BMhOVMDA2B54zADH$EQ9LuQwWXVaUrEWhypW9XVf+JjDdQP2f1ebasNR67d0=', max_length=128),
        ),
    ]
