# Generated by Django 5.2.4 on 2025-07-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$uOMDqUC0t5RcS7mShjn8CB$TRu6M3a42fqk4MOU9WYNUSQUUeI4blEV1wDz7a0mL5E=', max_length=128),
        ),
    ]
