# Generated by Django 5.2.4 on 2025-07-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$gWircSmvVAmcIsOauhSnei$oqVGfu/xHtnFbWXMpa6gC1BwjhQGiOtRueWD4V1FcBE=', max_length=128),
        ),
    ]
