# Generated by Django 5.2.4 on 2025-07-10 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mi_app', '0009_categoria_alter_usuario_password_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(db_index=True, default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$u7J6zFUsL9gealahplSDsl$7maYFbN+Zl8MVJnO6E3UTko7ybR/t+3qkLPFJZxI1DM=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(db_index=True, default='usuario', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(db_index=True, default='', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='zona_acceso',
            field=models.CharField(db_index=True, default='general', max_length=50),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol', 'zona_acceso'], name='usuarios_rol_a79849_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['created_at', 'is_active'], name='usuarios_created_d4f0cb_idx'),
        ),
    ]
