# Generated by Django 5.2.4 on 2025-07-15 02:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0011_alter_usuario_password_venta_ventaitem'),
    ]

    operations = [
        # Primero agregar los nuevos campos
        migrations.AddField(
            model_name='venta',
            name='cliente_cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='producto_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='venta_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Cambiar el nombre de la tabla
        migrations.AlterModelTable(
            name='ventaitem',
            table='detalles_venta',
        ),
        # Cambiar las opciones del modelo
        migrations.AlterModelOptions(
            name='ventaitem',
            options={'ordering': ['-created_at']},
        ),
    ]
