# Generated by Django 5.2.4 on 2025-07-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0012_auto_20250714_2134'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ventaitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='impuesto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$Mu2UOfzkNmxYY6FEPPZGC8$C427wgIloPNSUExcD+pjdmoYYMiE/spcxxP2rRUOMiQ=', max_length=128),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255)),
                ('usuario_id', models.UUIDField(blank=True, null=True)),
                ('producto_id', models.BigIntegerField()),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'carrito',
                'ordering': ['-created_at'],
                'unique_together': {('session_id', 'producto_id'), ('usuario_id', 'producto_id')},
            },
        ),
        migrations.RemoveField(
            model_name='ventaitem',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ventaitem',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='ventaitem',
            name='venta',
        ),
    ]
