# Generated by Django 5.2.4 on 2025-08-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0014_update_usuario_roles_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carrito',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$FMgpDxmFRdCDgg6qFcyN9G$eSb02Z84BQrKWkgNU4iRL/TZu82PemuyN4ARXJYY0UU=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(db_index=True, default='Usuario', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='carrito',
            constraint=models.UniqueConstraint(condition=models.Q(('usuario_id__isnull', True)), fields=('session_id', 'producto_id'), name='unique_session_producto'),
        ),
        migrations.AddConstraint(
            model_name='carrito',
            constraint=models.UniqueConstraint(condition=models.Q(('usuario_id__isnull', False)), fields=('usuario_id', 'producto_id'), name='unique_usuario_producto'),
        ),
    ]
