# Generated by Django 5.2.4 on 2025-08-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0015_alter_carrito_unique_together_alter_usuario_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$of1bof9HOgwGThh4C9CgQF$bDh3aPsZsF6uVgwvmrsMdaOi/sD3cYXWik8nFR7UHns=', max_length=128),
        ),
    ]
